FROM eclipse-temurin:21-jdk

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends inotify-tools maven && rm -rf /var/lib/apt/lists/*

COPY . .
RUN chmod +x mvnw

EXPOSE 8080

CMD ["sh", "./scripts/dev-entrypoint.sh"]
